// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avjfgrxsmadqhcvfgfbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2amZncnhzbWFkcWhjdmZnZmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTgwMjQsImV4cCI6MjA2NTI3NDAyNH0.Tnd8Hv8fZjJKsd1WcwbCcQzUlQlJ69mPcGIwo2O739Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);